<a href="https://colab.research.google.com/github/minjung00/Numpy/blob/main/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [1]:
import numpy as np

In [2]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [3]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [4]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [5]:
np.var(x), x.var()

(115.23224852071006, 115.23224852071006)

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값
<br>
$
s = \sqrt{s^2}
$

In [6]:
np.std(x), x.std()

(10.734628476137871, 10.734628476137871)

## 최댓값과 최솟값

In [8]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), x.max(), np.min(x), x.min()

(23, 23, -24, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [9]:
np.median(x) # 내장메소드 X

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [10]:
np.percentile(x, 0) # 최솟값, min

-24.0

In [11]:
np.percentile(x, 25) # 25% 백분위수, 1사분위수

0.0

In [15]:
np.percentile(x, 50)  # 50% 백분위수, 2사분위수, 중앙값

5.0

In [16]:
np.percentile(x, 75)  # 75% 백분위수, 3사분위수

10.0

In [17]:
np.percentile(x, 100)  # 100% 백분위수, 4사분위수, 최댓값

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [18]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [20]:
np.random.rand(5) # rand(n) : n개의 길이를 가지는 배열에 각각 0-1 사이의 난수를 채워줌

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [21]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.random.shuffle(x)  # x를 섞어줌 -> x
x

array([7, 8, 3, 6, 1, 5, 0, 4, 9, 2])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [25]:
np.random.choice(5, 5, replace=False) # 5개 중에 5개를 선택 -> 비복원

array([1, 4, 2, 3, 0])

In [26]:
np.random.choice(5, 3, replace=False) # 5개 중에 5개를 선택

array([0, 1, 4])

In [27]:
np.random.choice(5, 10, replace=True) # 복원, 5개 중에 10개를 선택 (뽑았던거 또 뽑는다)

array([4, 2, 0, 0, 4, 0, 4, 1, 4, 1])

In [29]:
#[0, 1, 2, 3, 4]
np.random.choice(5, 10, p=(0.1, 0, 0.3, 0.6, 0))

array([2, 0, 3, 3, 3, 3, 3, 3, 3, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [30]:
np.random.rand(10)

array([0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548,
       0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963])

In [31]:
np.random.rand(3, 5) # 3항, 5열

array([[0.971945  , 0.87819347, 0.50962438, 0.05571469, 0.45115921],
       [0.01998767, 0.44171092, 0.97958673, 0.35944446, 0.48089353],
       [0.68866118, 0.88047589, 0.91823547, 0.21682214, 0.56518887]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [33]:
np.random.randn(10)

array([ 0.02752832,  1.12060466, -0.22403878, -0.42018339,  0.99982969,
        0.43103415, -0.65091287, -1.49874039, -1.23063497,  0.19400719])

In [34]:
np.random.randn(3, 5)

array([[-0.99838235, -0.3676376 ,  1.73719932,  0.59361275, -0.54236358],
       [-1.71967238, -0.57890879,  1.42694855,  0.27699691,  0.78966713],
       [ 0.32207411,  0.70039238,  0.38871663, -0.04126386,  0.29588432]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [35]:
np.random.randint(10) # 최댓값보다 작은 범위에서 랜덤 숫자 (끝점 제외)
# np.random.randint(10, size=1)

9

In [36]:
np.random.randint(10, size=10) # 시작점

array([8, 0, 8, 5, 9, 0, 9, 6, 5, 3])

In [37]:
np.random.randint(10, 20, size=10)  # 시작점, 끝점

array([11, 18, 10, 14, 19, 16, 15, 17, 18, 18])

In [38]:
np.random.randint(10, 20, size=(3,5))

array([[19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18],
       [13, 12, 13, 16, 13]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [40]:
# 1
np.random.randint(2, size=10)

array([0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [47]:
# 1
np.random.choice(["Head","Tail"], size = 10, replace=True)

array(['Tail', 'Tail', 'Tail', 'Tail', 'Tail', 'Head', 'Head', 'Tail',
       'Head', 'Tail'], dtype='<U4')

In [49]:
# 2
x = np.random.randint(1, 7, size=100)
np.mean(x)

3.58

In [48]:
# 2
# np.random.randint(1, 7, 100)
# np.random.randint(1, 7, 100).mean()
np.random.choice(range(1,7), size=100, replace=True).mean()

3.62

In [53]:
# 3.
# np.random.randn(250)  # 정규분포
# 평균(기댓값)이 0이고 표준편차가 1인 정규분포 1%->0.01
a = np.random.randn(250)/100 # 일간 수익률이 표준정규분포표를 따르는 (0과 0.01이 표준편차)
a

array([-0.009073  ,  0.00224252, -0.01678688,  0.00214966,  0.00097219,
        0.01015665,  0.00701041, -0.00417477, -0.01097497,  0.01712305,
       -0.00792115, -0.01045525, -0.01084856,  0.01117305, -0.005189  ,
       -0.00753704,  0.0013769 , -0.00206945, -0.00678095,  0.00753991,
        0.01065315,  0.00985318,  0.0076692 ,  0.00402626, -0.01775888,
        0.01669251,  0.00301989,  0.00608156,  0.01114962,  0.01433353,
        0.00418398,  0.00435546, -0.00599224,  0.0003309 , -0.00854161,
       -0.00719941, -0.00893574, -0.00156024,  0.01049093,  0.03170975,
        0.001895  , -0.01348413,  0.01264983, -0.00300784, -0.00660609,
        0.00209849, -0.01240625,  0.00222463, -0.00088376,  0.00098378,
        0.00381416,  0.00067492,  0.00016338,  0.00284315,  0.00415401,
       -0.01031482, -0.01429991, -0.00061638, -0.01432735,  0.00087531,
        0.00938747,  0.00607112, -0.0104817 , -0.00860262,  0.00328301,
       -0.00401298, -0.00316655,  0.00596906, -0.00987287, -0.00

In [54]:
start = 10000  # 가격이 10000원 -> 250일 -> 평균/표준편차가 반영되면서 250일.
price = np.empty(250)  # 자리
for i, v in enumerate(a): # a -> 가격이 0의 기댓값, 1%의 표준편차를 바탕으로 250일치의 변화율이 생성
    start *= (1 + v)  # i = index, v = 변화율
    # -> 해당 금액의 변화율이 반영된 금액
    price[i] = start  # 변화율에 따라서 변경된 금액에 배열에 저장.
    # 한 번씩 for이 돌때마다 -> index += 1 => 계속 변화율이 반영된 금액들이 다음 인덱스에 저장

In [55]:
price

array([ 9909.26998785,  9931.49174588,  9764.77294968,  9785.76385153,
        9795.27749599,  9894.76472875,  9964.13112011,  9922.53312957,
        9813.6336604 ,  9981.67302197,  9902.60669066,  9799.07250592,
        9692.76667407,  9801.06447134,  9750.20672776,  9676.7189842 ,
        9690.04284172,  9669.98981061,  9604.41804864,  9676.83454118,
        9779.92335869,  9876.28665591,  9952.0298409 ,  9992.09925391,
        9814.65076231,  9978.48189931, 10008.615838  , 10069.48387853,
       10181.75482989, 10327.69526759, 10370.9061392 , 10416.07622257,
       10353.66056509, 10357.0865656 , 10268.62034441, 10194.69238446,
       10103.59522292, 10087.83120052, 10193.66195045, 10516.90039938,
       10536.82988752, 10394.74989428, 10526.24174762, 10494.58050964,
       10425.2524089 , 10447.12974665, 10317.52008506, 10340.47276669,
       10331.33431978, 10341.49807023, 10380.9422248 , 10387.94855703,
       10389.64574881, 10419.18502014, 10462.46637996, 10354.54787433,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [56]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [58]:
a = np.array(list('abbca'))
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [60]:
np.unique(a, return_counts=True) # 고윳값별로 추가값이 있는지 확인

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [62]:
index, value = np.unique(a, return_counts = True)
index, value

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [65]:
list(zip(index, value))  # 같은 인덱스에 있는 값끼리 튜플화시켜서 묶어줌
# index, value == *np.unique(a, return_counts=True)

[('a', 2), ('b', 2), ('c', 1)]

In [66]:
dict(zip(*np.unique(a, return_counts=True)))  # key, value

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [67]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 1 = 2, 2 = 3, 3 = 1

array([0, 2, 3, 1, 0, 0])