<a href="https://colab.research.google.com/github/minjung00/230619_numpy/blob/main/numpy_01_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy  기초

In [45]:
# pip install numpy
import numpy as np

In [46]:
#@title 1차원 배열
np.array([1, 2, 3])

array([1, 2, 3])

In [47]:
np.array(range(3))

array([0, 1, 2])

In [48]:
np.arange(3)

array([0, 1, 2])

In [49]:
#@title 벡터화 연산
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [52]:
a % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [53]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [54]:
(a > 5) & (a < 7)

array([False, False, False, False, False, False,  True, False, False,
       False])

In [55]:
#@title 2차원 배열
arr = np.array([[0, 1, 2], [3, 4, 5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
arr = np.arange(6).reshape(2, -1)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
arr, arr.ndim, arr.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [58]:
#@title 3차원배열
t = np.arange(24).reshape(2, 3, -1)
t, t.ndim, t.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 3,
 (2, 3, 4))

In [59]:
#@title 배열 복사
v = t.view()
c = t.copy()
t[0][0] = 100
t, v, c

(array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [60]:
#@title 배열의 인덱싱
# 일차원 배열 = 리스트의 인덱싱
a = np.arange(5)
print(a)
a[0], a[-1]

[0 1 2 3 4]


(0, 4)

In [61]:
# 다차원 배열 -> [] -> ,를 통해서 축을 구분
b = np.arange(6).reshape(2, -1)
b, b.ndim, b.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [62]:
b[0, 0]

0

In [63]:
b[0, 0] = 200
b

array([[200,   1,   2],
       [  3,   4,   5]])

In [64]:
#@title 배열 슬라이싱
# 다차원 배열 슬라이싱 -> 파이썬 슬라이싱 + 축(axis) ,를 같이 쓰면 된다
a = np.arange(8).reshape(2, -1)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
a[0], a[0, :]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [66]:
a[:, 1]

array([1, 5])

In [67]:
a[1, 1:]

array([5, 6, 7])

In [68]:
a[1:3, 0:2]

array([[4, 5]])

In [69]:
#@title 배열 인덱싱 (불리언 배열, 정수 배열)
# 불리언 배열
a1 = np.arange(1, 10, 2)
a2 = np.arange(1, 10)
a1, a2[a2 % 2 != 0], a2[::2]

(array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [70]:
#정수 배열
idx = np.arange(0, 9, 3)
idx, a2[idx]

(array([0, 3, 6]), array([1, 4, 7]))

In [71]:
import random

r = random.choices(range(len(a2)), k=20)
r, a2[r]

([4, 1, 1, 4, 0, 8, 4, 6, 0, 0, 6, 4, 7, 0, 7, 5, 2, 8, 0, 0],
 array([5, 2, 2, 5, 1, 9, 5, 7, 1, 1, 7, 5, 8, 1, 8, 6, 3, 9, 1, 1]))

In [72]:
#@title 다차원 배열에서의 배열 인덱싱
a = np.arange(1,13).reshape(3, -1)
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 2,
 (3, 4))

In [73]:
a[:,[3, 0]]

array([[ 4,  1],
       [ 8,  5],
       [12,  9]])

In [74]:
a[::-1, [3, 0]]

array([[12,  9],
       [ 8,  5],
       [ 4,  1]])

In [75]:
a[:, True, True, False, False]

array([], shape=(3, 0, 4), dtype=int64)

In [76]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [77]:
np.where(a % 2 ==0) #다차원 배열 -> 행렬로 인덱스

(array([0, 0, 1, 1, 2, 2]), array([1, 3, 1, 3, 1, 3]))

In [78]:
arr = np.arange(1, 9)
np.where(arr % 2 == 0)

(array([1, 3, 5, 7]),)

## 배열의 생성과 변형

In [79]:
x = np.arange(1, 4)
x, x.ndim, x.shape, x.dtype

(array([1, 2, 3]), 1, (3,), dtype('int64'))

In [80]:
x = np.arange(1.0, 4.0)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

In [81]:
x = np.arange(1.0, 4)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://sharegpt.com/c/YeSV33B

In [82]:
x = np.arange(1, 4, dtype='f')
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.], dtype=float32), 1, (3,), dtype('float32'))

In [83]:
np.inf  # 1/0 같은 무한대가 나오는 상황... (에러 안 나고...)

inf

In [84]:
np.nan  # 0/0 나누던가, nan(null)이 낀 연산 -> 값이 나올 수 없는 연산

nan

In [85]:
#@title 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [86]:
x = np.zeros((3, 5, 1))
x

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [87]:
np.zeros_like(x)

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [88]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [89]:
np.ones((3, 2, 5))  # 모양 -> 리스트, 튜플.

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [90]:
np.ones_like(x)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [91]:
np.empty(5)  # 값이 뭐가 나올지 몰라...

array([1., 1., 1., 1., 1.])

In [92]:
np.linspace(1, 10, 5) # 선형적으로 균등분배된 구간 (선형구간)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [93]:
np.logspace(0.1, 10, 5)

array([1.25892541e+00, 3.75837404e+02, 1.12201845e+05, 3.34965439e+07,
       1.00000000e+10])

In [94]:
A = np.arange(1, 7).reshape(2, -1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [96]:
A.reshape(-1)  # -1 => 전체 길이

array([1, 2, 3, 4, 5, 6])

In [97]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [98]:
x = np.arange(5)
x, x.shape

(array([0, 1, 2, 3, 4]), (5,))

In [99]:
x[:, np.newaxis], x[:, np.newaxis].shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

In [100]:
x[np.newaxis, :], x[np.newaxis, :].shape

(array([[0, 1, 2, 3, 4]]), (1, 5))

In [103]:
#@title 배열 연결
a = np.arange(1, 4)
b = np.arange(10, 13)
a, b

(array([1, 2, 3]), array([10, 11, 12]))

In [105]:
np.concatenate((a, b)) #axis = 0

array([ 1,  2,  3, 10, 11, 12])

In [107]:
np.concatenate((a, b), axis=0)
# np.concatenate((a, b), axis=1) <- 1차원

array([ 1,  2,  3, 10, 11, 12])

In [110]:
# hstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.hstack((a, b)), np.hstack((a, b)).shape, np.concatenate((a, b), axis=1)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]),
 (2, 6),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]))

In [ ]:
# vstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.vstack((a, b)), np.vstack((a, b)).shape, np.concatenate((a, b), axis=0)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 (4, 3),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [ ]:
# dstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.dstack((a, b)), np.dstack((a, b)).shape

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [ ]:
# stack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.stack((a, b)), np.stack((a, b)).shape  # axis=0

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 0
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=0

(array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 1
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=1

(array([[[1., 1., 1.],
         [0., 0., 0.]],
 
        [[1., 1., 1.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 2
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=2

(array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [ ]:
a = np.arange(1, 4)
b = np.arange(4, 7)
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [ ]:
np.tile(a, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
c = np.tile(a, (2, 2))
np.array_split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.array_split(c, 2, axis=0)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.array_split(c, 2, axis=1)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 3],
        [1, 2, 3]])]

In [109]:
# vstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.vstack((a, b)), np.vstack((a, b)).shape, np.concatenate((a, b), axis=0)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 (4, 3),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))